#!/bin/bash

# out
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
files=("ftdetect/diff.vim" "syntax/diff.vim")
for file in "${files[@]}"
do
	echo -ne "throwing ${file}...";
	cp "${DIR}/../${file}" "$HOME/.vim/plugged/Vim-Folddiff/${file}" &&
		echo -ne "success.\\n";
done

